import "./controls.ts";
import "../ui/menubar.ts";
import "../ui/editor.ts";
import "../interpreter/core/interpreter.ts";
import "../ui/resizers.ts";
import "../interpreter/lexer/lexer.ts";
import "../ui/contextmenu/contextmenu.ts";
import "../ui/explorer.ts";
import "../core/history.ts";
