name: "publish"

on:
    push:
        tags:
            - "v*"

jobs:
    publish-tauri:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - platform: "ubuntu-22.04"
                      args: ""
                    - platform: "windows-latest"
                      args: ""

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-22.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: setup bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: "./src-tauri -> target"

            - name: install frontend dependencies
              run: bun install

            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tagName: ${{ github.ref_name }}
                  releaseName: "ИСР КАРП ${{ github.ref_name }}"
                  releaseBody: |
                      # ИСР КАРП (${{ github.ref_name }})
                      Интегрированная среда разработки для обучения программированию на языке КАРП.

                      ## Установка
                      1. Скачай подходящий установщик для своей ОС в разделе ниже.
                      2. Для Windows запусти `.msi`, для Linux: `.deb` / `.AppImage`.
                  releaseDraft: false
                  prerelease: false
                  args: ${{ matrix.args }}
